# Twitter API Keys
TWITTER_CONSUMER_KEY = ""
TWITTER_CONSUMER_SECRET = ""
TWITTER_ACCESS_TOKEN = ""
TWITTER_ACCESS_TOKEN_SECRET = ""

# Reddit API Keys
REDDITT_ID = ""
REDDIT_SECRET = ""

# Discord API Keys
DISCORD_WEBHOOK_URL = ""
