# Twitter API Keys
TWITTER_CONSUMER_KEY = ""
TWITTER_CONSUMER_SECRET = ""
TWITTER_ACCESS_TOKEN = ""
TWITTER_ACCESS_TOKEN_SECRET = ""

# Reddit API Keys
REDDIT_CLIENT_ID = ""
REDDIT_CLIENT_SECRET = ""

# Discord API Keys
DISCORD_WEBHOOK_URL = ""
